#!/usr/bin/env python3
# -*- mode: python -*-
#
# Copyright (c) 2011-2020 The Electrum Develoers
# Copyright (c) 2013-2020 The btcsuite developers
# Copyright (c) 2015-2020 The Decred developers
# Copyright (c) 2019-2020 The atomicswap-qt developers
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
# BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
# ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import sys

from PyQt5.QtWidgets import QApplication
from PyQt5.QtGui import QIcon

from atomicswap.qt.main_window import MainWindow
from atomicswap.command import command
from atomicswap.util import get_path, resource_path


def qt_window():
    app = QApplication(sys.argv)
    app.setWindowIcon(QIcon(resource_path("qt", "icons", "icons8-swap.png")))
    ex = MainWindow()
    sys.exit(app.exec_())


if __name__ == "__main__":
    argv = sys.argv
    get_path()
    if len(argv) >= 2:
        qc = argv[1]
        qc = qc.lower()
        if qc == "command":
            try:
                cmd = argv[2]
                cmd = cmd.lower()
            except:
                command("help", [])
                exit()
            try:
                params = argv[3:]
            except:
                command("help", [])
                exit()
            command(cmd, params)
        elif qc == "help":
            command(qc, [])
        elif qc == "qt" or qc == "gui":
            qt_window()
        else:
            print(f"Invalid command: {qc}")
            command("help", [])
    else:
        qt_window()
